version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "genai-model-selection-demo"
s3_prefix = "genai-model-selection-demo"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = []
image_repositories = []
